layout_spectrum: 0.04806071
typography_spectrum: 0.3743676
color:
  lightness: 0.489882
  brandStrength: 0.09885974
  saturation: 0.4629005
  rhythmicContrast: 0.4758923
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Oyvindrs
